# Generated by Django 5.1.3 on 2024-11-22 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0004_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='cimage',
            field=models.ImageField(default='', upload_to='car_images/'),
        ),
    ]
