# Generated by Django 5.1.3 on 2024-11-22 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0005_car_cimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
