# Generated by Django 5.1.3 on 2024-11-22 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0006_delete_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stransmission', models.CharField(choices=[('Auto', 'Auto'), ('Manual', 'Manual')], max_length=10)),
                ('sfuel', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('EV', 'EV')], max_length=10)),
                ('cname', models.CharField(max_length=20)),
                ('cyear', models.IntegerField()),
                ('cprice', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('desc', models.TextField()),
                ('cimage', models.ImageField(default='', upload_to='car_images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carapp.user')),
            ],
        ),
    ]
