# Generated by Django 5.1.3 on 2024-12-11 03:56

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0007_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttime', models.TimeField(default=datetime.datetime(2024, 12, 11, 3, 56, 17, 412796, tzinfo=datetime.timezone.utc))),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carapp.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carapp.user')),
            ],
        ),
    ]
