# Generated by Django 5.1.4 on 2025-01-10 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='user',
            name='price',
        ),
        migrations.AddField(
            model_name='user',
            name='body',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='postId',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
